---
title: "Principal Components Analysis of five variables in the `state` dataset"
author: "Quin Smith"
date: "1/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages
library(tidyverse)
library(ggfortify)
library(janitor)
library(ggrepel)
library(RColorBrewer)
```

### Introduction

The `state` dataset is included within the `datasets` package that is pre-installed with R.  Data was 

```{r, message = FALSE, warning = FALSE}
#create a dataframe from dataset, state.x77 (included in base R)
states_df <- data.frame(state.x77) %>% 
  rownames_to_column(var = "State")

#test population density
states_df <- states_df %>% 
  mutate(density = Population / Area)

#convert the state.region (included in base R) from factor to character vector
region <- as.character(state.region)

#load state.abb (included in base R)
abbr <- state.abb

#append the region and state.abb (included in base r) vector to the state dataframe, clean names
states_df <- cbind(states_df, region, abbr) %>% 
  clean_names() %>% 
  column_to_rownames(var = 'abbr')
```

```{r, warning = FALSE, message = FALSE, fig.width = 9.5, fig.height=7.5}
#create palette
state_palette <- c("#7A871E", "#104210", "#E55B13", "#F6A21E")

#create the PCA plot
states_pca <- states_df %>% 
  select(income, illiteracy, life_exp, murder, hs_grad) %>% 
  scale() %>% 
  prcomp()


autoplot(states_pca,
         data = states_df,
         label.size = 3,
         colour = 'region',
         loadings = TRUE,
         loadings.label = TRUE,
         loadings.label.repel = TRUE,
         label.repel = TRUE) +
  scale_color_brewer(palette = "Set1") +
  theme_bw()
```

